import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import pickle

# Sample dataset (replace with your dataset)



''' casual
texts=["Hey, what’s up?",
       'Can you believe how cold it is today?','Wanna grab a bite to eat?',
       'Dude, that was awesome!',
       'What are you doing this weekend?',
       'I’m so tired of this rainy weather.',
       'Let’s binge-watch a series tonight.',
       'OMG, you won’t believe what happened!',
       'I’m totally hooked on this new song.',
       'Do you think I should get pizza or burgers?',
       'Ugh, I hate Mondays.',
       'You’re not gonna believe this crazy story.',
       'I’ll text you when I’m on the way.',
       'This new phone is pretty cool, huh?',
       'Wanna meet up at the park later?',
       'I can’t stop laughing at this meme.',
       'Is it just me, or does this coffee taste weird?',
       'I’m so over this traffic.',
       'What’s the plan for tonight?',
       'That was so random, but I loved it.',
       'I’m gonna crash early tonight, so tired.',
       'Can you help me with this thing real quick?',
       'I’m feeling kinda lazy today.',
       'Why is everything so expensive these days?',
       'I can’t believe I forgot my keys again.',
       'You’ve gotta try this new place I found.',
       'That outfit looks amazing on you!',
       'I’ll call you back in five minutes, promise.',
       'Seriously, I’m addicted to this show.',
       'I’m starving, let’s get something to eat.',
       'Whoa, check out that sunset!',
       'Did you see that crazy video?',
       'I can’t wait for the weekend to get here.',
       'Let’s go for a walk and clear our heads.',
       'Are you free to hang out tomorrow?',
       'This app keeps crashing, so annoying.',
       'I just need five more minutes of sleep.',
       'I can’t stop thinking about last night’s game.',
       'Wanna split a dessert?',
       'Why does time fly so fast when you’re having fun?',
       'Let’s take a selfie!',
       'You’ve gotta tell me where you got that shirt.',
       'I’m gonna miss you so much.',
       'Can you believe we’ve known each other for so long?',
       'This is so unfair, I can’t even.',
       'I need coffee, like, right now.',
       'Let’s try something new today.',
       'I’ve been rewatching my favorite series all day.',
       'Can you grab me a drink while you’re at it?',
       'I’m so done with this day.',
       'Do you remember that time we got lost?',
       'That sounds like a plan!',
       'You’re seriously the best.',
       'Wanna join me for a quick workout?',
       'I can’t decide what to wear tonight.',
       'What’s your favorite kind of music?',
       'This place is so chill, I love it.',
       'I feel like I’ve been here before.',
       'Let’s order takeout and relax.',
       'You’ve gotta hear this new joke I learned.',
       'I can’t believe we’re finally here!',
       'I’m so glad we did this.',
       'That’s hilarious, tell me more!',
       'I’m obsessed with this new app.',
       'Can you help me pick out a gift?',
       'Let’s hit the road early tomorrow.',
       'You know I always have your back, right?',
       'I’m so nervous about this presentation.',
       'Why is everything so complicated these days?',
       'Let’s grab some ice cream and chat.',
       'I can’t stop thinking about that trip.',
       'Can you believe how fast this year went by?',
       'I really needed that laugh today.',
       'I’m so ready for a vacation.',
       'That’s so cool, tell me more!',
       'I’m feeling pretty good about this.',
       'Wanna come over and chill?',
       'Why is this so much harder than it looks?',
       'Let’s try cooking something fun tonight.',
       'I’m totally up for it.',
       'That’s exactly what I was thinking!',
       'Do you think it’s gonna rain later?',
       'I’ve got so much to tell you.',
       'This is such a vibe.',
       'I’m so proud of you, seriously.',
       'You’re not gonna believe this, but…',
       'I just want to relax and do nothing today.',
       'Wanna go for a drive and play some music?',
       'I’m always here if you need me.',
       'Let’s make plans for next weekend.',
       'You always know how to cheer me up.',
       'I’ve been looking forward to this all week.',
       'Can we take a break?',
       'I can’t believe how good this tastes!',
       'That’s exactly what I needed to hear.',
       'I’ll see you soon, take care.',
       'This is so much fun, let’s do it again.',
       'You’ve got great taste in music.',
       "I’m so happy we’re friends.",
       "Wanna grab coffee and catch up?"
    ]
'''
''' formal
texts = [
    "I am writing to express my interest in the position advertised on your website.",
    "Please let me know a convenient time for us to discuss the matter further.",
    "Your assistance in resolving this issue would be greatly appreciated.",
    "Thank you for taking the time to consider my application.",
    "I look forward to your response at your earliest convenience.",
    "Attached are the documents required for your review.",
    "It would be an honor to collaborate on this project with your esteemed organization.",
    "I appreciate your prompt attention to this matter.",
    "Please do not hesitate to reach out if you require additional information.",
    "I hope this message finds you well and in good health.",
    "Your feedback on this proposal would be greatly valued.",
    "Thank you for your continued support and guidance.",
    "This email is to confirm our scheduled meeting on Monday at 10:00 AM.",
    "We would be delighted to host you at our event next month.",
    "It is imperative that we address this concern promptly.",
    "I would appreciate it if you could provide further clarification on this matter.",
    "Please let us know if there is anything else we can do to assist you.",
    "I kindly request an update regarding the progress of the project.",
    "Your expertise in this domain would be invaluable to the team.",
    "I am grateful for the opportunity to present my ideas to the panel.",
    "The information provided in your report was highly insightful and well-received.",
    "I am looking forward to hearing your thoughts on this matter.",
    "It was a pleasure meeting you at the recent conference.",
    "Your dedication to excellence is truly commendable.",
    "Please find below the details of the upcoming seminar for your reference.",
    "I hope to contribute to the success of the organization through my skills and experience.",
    "It would be greatly appreciated if you could confirm your availability for the meeting.",
    "I am writing to follow up on our previous correspondence regarding this matter.",
    "Thank you for bringing this to our attention.",
    "I am confident that this partnership will yield mutually beneficial results.",
    "We remain committed to delivering the highest quality services to our clients.",
    "Please let us know if there are any specific requirements we should consider.",
    "The purpose of this email is to request your guidance on the proposed changes.",
    "Thank you for the opportunity to work on such an impactful project.",
    "We are pleased to announce the launch of our new initiative.",
    "Your opinion is highly valued, and we welcome your suggestions.",
    "It was a privilege to work alongside such talented colleagues.",
    "I am reaching out to seek your assistance in resolving this issue.",
    "We would like to extend our heartfelt gratitude for your continued trust in our services.",
    "Your proactive approach to problem-solving is truly admirable.",
    "I would be happy to provide further details if required.",
    "We are committed to ensuring the highest standards of quality and professionalism.",
    "I am writing to formally request a meeting to discuss this matter further.",
    "Your insights and recommendations will greatly enhance our strategy.",
    "I am confident that our collective efforts will lead to a successful outcome.",
    "Thank you for your patience and understanding during this process.",
    "Please let us know if you require any further assistance.",
    "We look forward to your valuable input on the proposed plan.",
    "Your attention to detail and dedication to excellence are greatly appreciated.",
    "This letter serves as a formal notice regarding the change in schedule.",
    "It was a pleasure to attend the workshop organized by your team.",
    "Thank you for considering our proposal for the upcoming project.",
    "We are eager to explore potential opportunities for collaboration.",
    "I would like to schedule a call to discuss the next steps in this process.",
    "The progress achieved so far is commendable and deserves recognition.",
    "Your cooperation in this matter is highly valued.",
    "I am pleased to inform you that your application has been approved.",
    "Your constructive feedback has been instrumental in shaping our strategy.",
    "It is with great enthusiasm that I submit this proposal for your review.",
    "I look forward to building a strong professional relationship with your organization.",
    "Your commitment to excellence is an inspiration to us all.",
    "We appreciate your willingness to assist us with this initiative.",
    "The details of the contract are outlined in the attached document.",
    "Thank you for your prompt response to our inquiry.",
    "Your contributions to the success of this project are greatly acknowledged.",
    "We are confident that this collaboration will yield positive results.",
    "It is essential that we adhere to the outlined timelines for this project.",
    "Thank you for your continued dedication to this endeavor.",
    "We appreciate your support and guidance throughout this process.",
    "Please find attached the agenda for our upcoming meeting.",
    "I am writing to request an update regarding the status of this project.",
    "Your expertise in this area has been invaluable to the team.",
    "It was a pleasure to receive your input during our recent discussion.",
    "We remain committed to achieving the goals outlined in our proposal.",
    "I am looking forward to your response on the proposed changes.",
    "Your assistance in streamlining this process would be greatly appreciated.",
    "I am writing to formally acknowledge receipt of your correspondence.",
    "The insights shared during our meeting were highly valuable.",
    "We would be delighted to welcome you as a guest speaker at our event.",
    "Your unwavering support has been a cornerstone of our success.",
    "Please let us know if you have any additional requirements.",
    "Your positive feedback is greatly appreciated and encourages us to strive for excellence.",
    "We look forward to collaborating with you on future endeavors.",
    "Thank you for your valuable contributions to this discussion.",
    "Your dedication and hard work have not gone unnoticed.",
    "The team has made significant progress on the assigned tasks.",
    "We are pleased to confirm your participation in the upcoming event.",
    "Your efforts in ensuring the success of this project are greatly appreciated.",
    "Please let us know if there are any adjustments to be made.",
    "Thank you for the opportunity to contribute to such an impactful initiative.",
    "We value your insights and look forward to your continued involvement.",
    "Your professionalism and expertise set a high standard for others to follow.",
    "It is always a pleasure to work with individuals who are so committed to excellence.",
    "Thank you for providing such detailed and comprehensive feedback.",
    "We are optimistic about the outcomes of this collaborative effort.",
    "Your guidance and mentorship have been pivotal to our success.",
    "Please feel free to reach out with any further questions or concerns.",
    "Your enthusiasm and passion for this project are truly inspiring.",
]
'''
'''technical'''
texts = [
    "The software requires a minimum of 8 GB of RAM to function optimally.",
    "The system architecture is based on a microservices model for scalability.",
    "A RESTful API was implemented to enable seamless communication between components.",
    "The database schema includes tables for users, transactions, and logs.",
    "The application uses OAuth 2.0 for secure user authentication.",
    "Anomaly detection algorithms were integrated to identify potential security threats.",
    "The front-end framework chosen for this project is React.js.",
    "A continuous integration pipeline was established using Jenkins.",
    "The encryption protocol used for data transmission is AES-256.",
    "Unit tests were written to achieve 95% code coverage.",
    "Docker containers were utilized to ensure consistent deployment across environments.",
    "The system relies on a distributed ledger for maintaining data integrity.",
    "Data preprocessing steps included normalization and outlier detection.",
    "The machine learning model was trained using TensorFlow and Keras.",
    "The network topology consists of multiple subnets for improved security.",
    "Git is used for version control to manage source code changes.",
    "The application implements a role-based access control mechanism.",
    "A load balancer distributes incoming traffic to multiple server instances.",
    "The caching mechanism reduces database load and improves response times.",
    "A decision tree classifier was used for predictive analysis.",
    "Performance benchmarks indicate a 20% improvement in processing speed.",
    "The software employs a modular design for easier maintenance and updates.",
    "Log files are stored in a centralized repository for analysis.",
    "Error handling mechanisms ensure graceful recovery from unexpected failures.",
    "The user interface complies with accessibility standards, including WCAG 2.1.",
    "The system supports horizontal scaling to accommodate increased load.",
    "A time complexity analysis was performed for the sorting algorithm.",
    "The configuration files are managed using YAML for readability.",
    "A regression model was used to predict future trends based on historical data.",
    "The data pipeline includes ETL processes for seamless integration.",
    "Code reviews are conducted regularly to ensure adherence to best practices.",
    "A hybrid cloud approach was adopted to leverage both public and private resources.",
    "Network latency was reduced by optimizing the routing protocol.",
    "The software supports multi-threading to handle concurrent requests.",
    "APIs were documented using Swagger for developer reference.",
    "The system employs Kubernetes for container orchestration.",
    "A convolutional neural network was used for image classification tasks.",
    "The server uses NGINX as a reverse proxy for handling requests.",
    "SQL queries were optimized to minimize execution time.",
    "The application is compatible with both Android and iOS platforms.",
    "Data augmentation techniques improved the model's accuracy by 10%.",
    "The deployment process is automated using Ansible scripts.",
    "Real-time analytics are performed using Apache Kafka and Spark.",
    "The system logs include timestamps for accurate event tracking.",
    "Backpropagation was used to optimize the neural network weights.",
    "The software adheres to the principles of object-oriented programming.",
    "The system supports API rate limiting to prevent abuse.",
    "A gradient boosting algorithm was used for classification tasks.",
    "The codebase follows the PEP 8 style guide for Python.",
    "The application includes localization features for multiple languages.",
    "The system uses a star schema for efficient data warehousing.",
    "The model's performance was evaluated using precision, recall, and F1-score.",
    "The application supports two-factor authentication for enhanced security.",
    "Memory leaks were identified and resolved during testing.",
    "The software is designed to handle high-availability scenarios.",
    "The application uses a GraphQL API for flexible data queries.",
    "Key-value pairs are stored in a NoSQL database for rapid access.",
    "The neural network was trained using stochastic gradient descent.",
    "Data visualization was performed using Matplotlib and Seaborn libraries.",
    "A cluster of servers ensures redundancy and fault tolerance.",
    "The application is hosted on AWS with auto-scaling enabled.",
    "System performance is monitored using Prometheus and Grafana.",
    "Tokenization was applied to preprocess the text data for NLP tasks.",
    "The application uses asynchronous programming to improve efficiency.",
    "An API gateway manages incoming API requests and responses.",
    "Hyperparameter tuning improved the model's accuracy by 15%.",
    "The system performs periodic backups to prevent data loss.",
    "A confusion matrix was used to analyze the classification results.",
    "The software includes a logging framework for error tracking.",
    "Docker Compose simplifies multi-container application deployment.",
    "Feature engineering enhanced the predictive power of the model.",
    "The model was trained on a GPU to accelerate computation.",
    "The application uses a pub-sub model for real-time notifications.",
    "The web application complies with the OWASP security standards.",
    "The REST API uses HTTP status codes to communicate errors.",
    "A random forest classifier was used for the prediction task.",
    "The database uses indexing to speed up query execution.",
    "Continuous delivery is implemented for rapid deployment of updates.",
    "The application supports dynamic theming for better user customization.",
    "The feature extraction process was automated for efficiency.",
    "Cross-validation was used to evaluate the machine learning model.",
    "The system uses serverless architecture for certain microservices.",
    "A dropout layer was added to the model to prevent overfitting.",
    "Real-time streaming data is processed using Apache Flink.",
    "The application implements a secure payment gateway integration.",
    "A Bayesian network was used for probabilistic reasoning.",
    "Time series analysis was conducted to forecast future demand.",
    "The chatbot uses a transformer model for conversational AI.",
    "The application leverages Redis for caching frequently accessed data.",
    "The system uses Elasticsearch for fast text-based searches.",
    "Hyperledger Fabric is used for the blockchain implementation.",
    "The application supports progressive web app features for offline use.",
    "The dataset was balanced using SMOTE to improve model performance.",
    "Multi-factor authentication was implemented to enhance system security.",
    "Regular expressions were used to parse and validate input data.",
    "The project uses GitHub Actions for continuous integration workflows.",
    "The software design follows the MVC architectural pattern.",
    "The API response time was reduced by optimizing database queries.",
]

'''
texts = [
    "I hope this email finds you well.",
    "Could you please confirm receipt of this message?",
    "Thank you for your prompt response.",
    "I am reaching out to follow up on our previous discussion.",
    "Please let me know if you have any questions or concerns.",
    "Attached, you will find the requested documents.",
    "Looking forward to your reply at your earliest convenience.",
    "Thank you for your attention to this matter.",
    "I am writing to provide an update on the project status.",
    "Kindly share your availability for a meeting next week.",
    "It was a pleasure meeting you at the recent conference.",
    "I would like to schedule a call to discuss this further.",
    "Please advise on the next steps.",
    "I appreciate your assistance with this request.",
    "We would be grateful if you could provide your feedback.",
    "Thank you for bringing this issue to our attention.",
    "Could you please share the latest version of the document?",
    "I have copied my colleague on this email for additional support.",
    "Please let us know how we can assist further.",
    "I am writing to inquire about the timeline for completion.",
    "We are pleased to inform you about the upcoming event.",
    "Kindly confirm if the proposed date works for you.",
    "We appreciate your cooperation and support.",
    "Please find below the details of the upcoming meeting.",
    "Let me know if there’s anything else I can assist with.",
    "I wanted to check in regarding the status of the report.",
    "We are excited to invite you to our annual conference.",
    "Thank you for your kind words and encouragement.",
    "Could you provide clarification on the following points?",
    "Please let us know if you require any additional information.",
    "I am writing to formally request approval for the proposal.",
    "Your input on this matter would be greatly valued.",
    "We are looking forward to collaborating with you on this project.",
    "Kindly review the attached file and share your feedback.",
    "Please let me know if this schedule aligns with your availability.",
    "I am happy to assist with any further details you may need.",
    "We appreciate your patience as we work through this process.",
    "Please let me know if this email has reached you.",
    "I wanted to take a moment to thank you for your efforts.",
    "We are reaching out to remind you about the upcoming deadline.",
    "Let us know if there’s a convenient time for a quick call.",
    "Thank you for providing your insights during the meeting.",
    "Could you confirm the delivery date for the shipment?",
    "We are grateful for your continued partnership.",
    "Please find the meeting agenda attached for your reference.",
    "I would appreciate it if you could review the following details.",
    "Thank you for your understanding and support.",
    "This is a gentle reminder regarding the pending approval.",
    "Please provide an update on the progress of the assigned tasks.",
    "We would like to express our gratitude for your hard work.",
    "Could you share your thoughts on the proposed plan?",
    "Please inform us if any adjustments are required.",
    "I am writing to share an update on the recent developments.",
    "Your feedback on the draft would be greatly appreciated.",
    "We hope you find this information helpful.",
    "Thank you for taking the time to review this proposal.",
    "I am available for a discussion at your earliest convenience.",
    "Please don’t hesitate to reach out if you have any questions.",
    "Could you provide your input on the attached presentation?",
    "Thank you for bringing this to my attention.",
    "We are writing to inform you of a change in schedule.",
    "Please let us know your thoughts on this proposal.",
    "I look forward to hearing from you soon.",
    "Your assistance in this matter is greatly appreciated.",
    "We are excited to share the good news with you.",
    "Kindly let us know if you require any further clarification.",
    "I hope this email answers your questions.",
    "Please share your availability for the proposed dates.",
    "Thank you for your continued trust and support.",
    "I am writing to remind you about the upcoming meeting.",
    "We would appreciate it if you could provide an update.",
    "Your response to this inquiry would be greatly valued.",
    "Please find below the key highlights of the discussion.",
    "I hope you had a chance to review the document I shared.",
    "Could you kindly share the details of the next steps?",
    "Thank you for considering our request.",
    "I wanted to express my appreciation for your collaboration.",
    "This email serves as a confirmation of our agreement.",
    "We look forward to your participation in the event.",
    "Kindly let me know if this aligns with your expectations.",
    "I am following up to ensure everything is on track.",
    "We are writing to notify you of the recent updates.",
    "Your prompt response would be greatly appreciated.",
    "I wanted to provide a quick update on the pending tasks.",
    "Please let us know if there are any changes to the timeline.",
    "We are happy to assist with any queries you may have.",
    "Could you confirm if this proposal meets your requirements?",
    "Thank you for your continued dedication to the project.",
    "Please share the final draft once it’s ready.",
    "We are looking forward to your valuable contributions.",
    "I am writing to confirm our meeting scheduled for tomorrow.",
    "Thank you for your detailed explanation during the call.",
    "We would like to ensure a smooth transition for the team.",
    "Your suggestions would be greatly appreciated for this initiative.",
    "Let me know if there’s anything else you’d like to discuss.",
]

'''



# Hyperparameters
max_vocab_size = 5000
max_sequence_length = 10
embedding_dim = 100


# Initialize the tokenizer
tokenizer = Tokenizer(num_words=max_vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(texts)

# Convert text to sequences
sequences = tokenizer.texts_to_sequences(texts)

# Prepare input (X) and output (Y)
X = []
Y = []

for seq in sequences:
    for i in range(1, len(seq)):
        X.append(seq[:i])  # Input is all tokens up to position `i`
        Y.append(seq[i])   # Output is the next token

# Pad sequences for consistent input shape
X = pad_sequences(X, maxlen=max_sequence_length, padding='pre')
Y = np.array(Y)

# Vocabulary size
vocab_size = len(tokenizer.word_index) + 1


model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_sequence_length),
    LSTM(150, return_sequences=False),
    Dense(vocab_size, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

print(model.summary())



# Train the model
model.fit(X, Y, epochs=100, verbose=1)


# Save the trained model
model.save('models/technical_model.h5')  # Replace 'casual_model' with the relevant style

# Save the tokenizer
with open('models/technical_tokenizer.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)


